export const strings = {
  windowTitle: "东方演舞壁纸",
  btnApply: "应用",
  btnFavorite: "收藏",
  btnRandom: "换一张",
  labelCurrentWallpaper: "当前壁纸",
  noCurrentWallpaper: "（未设置或无法读取系统壁纸）",
  applyFailed: "设壁纸失败",
  labelPreview: "预览",
  labelVariants: "立绘变体",
  labelCharacters: "角色",
  sidebarScrollHint: "滚轮滚动列表",
  btnPrevCharacter: "上一个角色",
  btnNextCharacter: "下一个角色",
  favoriteOn: "取消收藏",
  favoriteOff: "收藏",
  btnFavoritesOnly: "只看收藏",
  favoritesOnlyEmpty: "请至少收藏一张图片",
  labelFavoritesGallery: "收藏",
  downloadHint: "首次使用请运行下载脚本获取立绘资源",
  emptyAssets: "未找到立绘资源",
  downloadWelcome: "欢迎使用东方演舞壁纸",
  downloadExplain:
    "安装已完成。首次使用需下载立绘资源（约 591 张），下载完成后即可离线使用。",
  downloadCheckNetwork: "请保持网络连接",
  downloadCheckDisk: "需要约 50MB 磁盘空间",
  downloadCheckTime: "预计需要几分钟",
  downloadStart: "开始下载",
  downloadProgress: "下载进度：",
  downloadCredit: "图片来源：thpdp.ver.moe · 幻想人形演舞（个人使用）",
  scaffoldNote: "M0 骨架：功能尚未接入",
} as const;

export const theme = {
  background: "#F8FBFF",
  surface: "#FFFFFF",
  primary: "#2563EB",
  primaryHover: "#1D4ED8",
  text: "#1E293B",
  textMuted: "#64748B",
  border: "#E2E8F0",
  gridSelected: "#DBEAFE",
} as const;
